name: ur-simulation-suite
services:
  ursim-service:
    env_file: ursim.env
    build:
      context: .
      dockerfile: Dockerfile
    image: ursim:lastest
    container_name: ursim-container
    # volumes:
    #   - ../programs:/ursim/programs
    ports:
      - 29999:29999
      - 6080:6080
      - 30001:30001
      - 30004:30004
      - 30002:30002
      - 50002:50002
    # robodk-service:
    #   container_name: robodk-container
    #   image: robodk/robodk
