name: ursim-suite
services:
  ursim-service:
    container_name: ursim-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POLYSCOPE=${POLYSCOPE}
    volumes:
      - ./programs:/ursim/programs
      - ./urcaps:/urcaps
    ports:
      - 29999:29999
      - 6080:6080
      - 30001:30001
      - 30004:30004
      - 30002:30002
      - 50002:50002
    environment:
      - ROBOT_MODEL=${ROBOT_MODEL}
      - TZ=${TIMEZONE}
  robodk-service:
    container_name: robodk-container
    image: robodk/robodk
